"""create core banking domain models

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                name="customer_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(trim(full_name)) > 0", name=op.f("ck_customers_full_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("email", name=op.f("uq_customers_email")),
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_customers_status"), "customers", ["status"], unique=False, schema="bankflow"
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("account_number", sa.String(length=32), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "checking",
                "savings",
                name="account_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "frozen",
                "closed",
                name="account_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "balance",
            sa.Numeric(precision=18, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name=op.f("ck_accounts_balance_nonnegative")),
        sa.CheckConstraint(
            "char_length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_accounts_currency_iso_style"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_accounts_version_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["bankflow.customers.id"],
            name=op.f("fk_accounts_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("account_number", name=op.f("uq_accounts_account_number")),
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_accounts_customer_id"),
        "accounts",
        ["customer_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_accounts_status"), "accounts", ["status"], unique=False, schema="bankflow"
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("card_token", sa.String(length=64), nullable=False),
        sa.Column("last_four", sa.String(length=4), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "locked",
                "expired",
                "inactive",
                name="card_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("expiry_month", sa.Integer(), nullable=False),
        sa.Column("expiry_year", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("last_four ~ '^[0-9]{4}$'", name=op.f("ck_cards_last_four_digits")),
        sa.CheckConstraint("char_length(pin_hash) >= 32", name=op.f("ck_cards_pin_hash_present")),
        sa.CheckConstraint(
            "expiry_month BETWEEN 1 AND 12", name=op.f("ck_cards_expiry_month_range")
        ),
        sa.CheckConstraint(
            "expiry_year BETWEEN 2000 AND 9999", name=op.f("ck_cards_expiry_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bankflow.accounts.id"],
            name=op.f("fk_cards_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("card_token", name=op.f("uq_cards_card_token")),
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_cards_account_id"), "cards", ["account_id"], unique=False, schema="bankflow"
    )
    op.create_index(op.f("ix_cards_status"), "cards", ["status"], unique=False, schema="bankflow")
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "balance_inquiry",
                "withdrawal",
                "deposit",
                name="transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "completed",
                "declined",
                "failed",
                name="transaction_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("decline_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0 OR (transaction_type = 'balance_inquiry' AND amount = 0)",
            name=op.f("ck_transactions_amount_matches_type"),
        ),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_transactions_balance_after_nonnegative")
        ),
        sa.CheckConstraint(
            "balance_before >= 0", name=op.f("ck_transactions_balance_before_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bankflow.accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["bankflow.cards.id"],
            name=op.f("fk_transactions_card_id_cards"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        schema="bankflow",
    )
    op.create_index(
        "ix_transactions_account_created_at",
        "transactions",
        ["account_id", "created_at"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_transactions_card_id"),
        "transactions",
        ["card_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False, schema="bankflow"
    )
    op.create_index(
        op.f("ix_transactions_transaction_type"),
        "transactions",
        ["transaction_type"],
        unique=False,
        schema="bankflow",
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bankflow.accounts.id"],
            name=op.f("fk_audit_events_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["bankflow.cards.id"],
            name=op.f("fk_audit_events_card_id_cards"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["bankflow.customers.id"],
            name=op.f("fk_audit_events_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["bankflow.transactions.id"],
            name=op.f("fk_audit_events_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_audit_events_account_id"),
        "audit_events",
        ["account_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_audit_events_card_id"),
        "audit_events",
        ["card_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_audit_events_customer_id"),
        "audit_events",
        ["customer_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        op.f("ix_audit_events_transaction_id"),
        "audit_events",
        ["transaction_id"],
        unique=False,
        schema="bankflow",
    )
    op.create_index(
        "ix_audit_events_type_created_at",
        "audit_events",
        ["event_type", "created_at"],
        unique=False,
        schema="bankflow",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_type_created_at", table_name="audit_events", schema="bankflow")
    op.drop_index(
        op.f("ix_audit_events_transaction_id"), table_name="audit_events", schema="bankflow"
    )
    op.drop_index(op.f("ix_audit_events_customer_id"), table_name="audit_events", schema="bankflow")
    op.drop_index(op.f("ix_audit_events_card_id"), table_name="audit_events", schema="bankflow")
    op.drop_index(op.f("ix_audit_events_account_id"), table_name="audit_events", schema="bankflow")
    op.drop_table("audit_events", schema="bankflow")
    op.drop_index(
        op.f("ix_transactions_transaction_type"), table_name="transactions", schema="bankflow"
    )
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions", schema="bankflow")
    op.drop_index(op.f("ix_transactions_card_id"), table_name="transactions", schema="bankflow")
    op.drop_index(
        "ix_transactions_account_created_at", table_name="transactions", schema="bankflow"
    )
    op.drop_table("transactions", schema="bankflow")
    op.drop_index(op.f("ix_cards_status"), table_name="cards", schema="bankflow")
    op.drop_index(op.f("ix_cards_account_id"), table_name="cards", schema="bankflow")
    op.drop_table("cards", schema="bankflow")
    op.drop_index(op.f("ix_accounts_status"), table_name="accounts", schema="bankflow")
    op.drop_index(op.f("ix_accounts_customer_id"), table_name="accounts", schema="bankflow")
    op.drop_table("accounts", schema="bankflow")
    op.drop_index(op.f("ix_customers_status"), table_name="customers", schema="bankflow")
    op.drop_table("customers", schema="bankflow")
    # ### end Alembic commands ###
